apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-depl
spec:
  replicas: 3 #2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server
          image: ernst1/http-server
          env:
          - name: SERVICE_NAME
            value: http-server
          - name: SERVICE_TAGS
            value: http
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  type: LoadBalancer
  selector:
    app: http-server
  ports:
    - name: http-server
      protocol: TCP
      port: 8080
      targetPort: 8080
